import { defineConfig } from "astro/config";

export default defineConfig({
  site: "https://willduet.com",
  redirects: {
    "/rd/conferencia-analista-datos": "/academy/ads/conferencia-analista-datos/",
    "/rd/insercion-laboral-analisis-de-datos-abril-2026": "/academy/ads/insercion-laboral-analisis-de-datos-abril-2026/",
    "/academy/eventos/conferencia-analista-datos": "/academy/ads/conferencia-analista-datos/",
    "/academy/eventos/insercion-laboral-analisis-de-datos-abril-2026": "/academy/ads/insercion-laboral-analisis-de-datos-abril-2026/",
    "/services": "/consulting/services/",
    "/contact": "/consulting/contact/",
    "/power-bi-consulting": "/consulting/power-bi-consulting/",
    "/power-bi-dashboard-development": "/consulting/power-bi-dashboard-development/",
    "/power-bi-training": "/consulting/power-bi-training/",
    "/data-engineering-consulting": "/consulting/data-engineering-consulting/",
    "/analytics-engineering-consulting": "/consulting/analytics-engineering-consulting/",
    "/blogs": "/consulting/blogs/",
    "/blogs/common-dashboard-design-mistakes": "/consulting/blogs/common-dashboard-design-mistakes/",
    "/blogs/database-vs-data-warehouse": "/consulting/blogs/database-vs-data-warehouse/",
    "/blogs/executive-dashboard-design-best-practices": "/consulting/blogs/executive-dashboard-design-best-practices/",
    "/blogs/hire-power-bi-consultant-vs-in-house": "/consulting/blogs/hire-power-bi-consultant-vs-in-house/",
    "/blogs/how-to-create-automated-business-reports": "/consulting/blogs/how-to-create-automated-business-reports/",
    "/blogs/how-to-optimize-slow-power-bi-reports": "/consulting/blogs/how-to-optimize-slow-power-bi-reports/",
    "/blogs/kpi-dashboard-design-best-practices": "/consulting/blogs/kpi-dashboard-design-best-practices/",
    "/blogs/power-bi-consultant-vs-in-house-bi-team": "/consulting/blogs/power-bi-consultant-vs-in-house-bi-team/",
    "/blogs/power-bi-consulting-services": "/consulting/blogs/power-bi-consulting-services/",
    "/blogs/power-bi-dashboard-best-practices": "/consulting/blogs/power-bi-dashboard-best-practices/",
    "/blogs/power-bi-dashboard-development-services": "/consulting/blogs/power-bi-dashboard-development-services/",
    "/blogs/power-bi-governance": "/consulting/blogs/power-bi-governance/",
    "/blogs/power-bi-implementation-challenges": "/consulting/blogs/power-bi-implementation-challenges/",
    "/blogs/power-bi-implementation-checklist": "/consulting/blogs/power-bi-implementation-checklist/",
    "/blogs/power-bi-implementation-cost": "/consulting/blogs/power-bi-implementation-cost/",
    "/blogs/power-bi-implementation-guide": "/consulting/blogs/power-bi-implementation-guide/",
    "/blogs/power-bi-implementation-partner": "/consulting/blogs/power-bi-implementation-partner/",
    "/blogs/power-bi-performance-optimization": "/consulting/blogs/power-bi-performance-optimization/",
    "/blogs/power-bi-pro-vs-premium": "/consulting/blogs/power-bi-pro-vs-premium/",
    "/blogs/power-bi-reports-vs-dashboards": "/consulting/blogs/power-bi-reports-vs-dashboards/",
    "/blogs/power-bi-security-best-practices": "/consulting/blogs/power-bi-security-best-practices/",
    "/blogs/power-bi-vs-excel": "/consulting/blogs/power-bi-vs-excel/",
    "/blogs/what-does-a-power-bi-consultant-do": "/consulting/blogs/what-does-a-power-bi-consultant-do/",
  },
});
